# Generated by Django 5.2.5 on 2025-09-01 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='votes',
        ),
        migrations.AddField(
            model_name='report',
            name='downvotes_count',
            field=models.IntegerField(default=0, verbose_name='Downvotes count'),
        ),
        migrations.AddField(
            model_name='report',
            name='upvotes_count',
            field=models.IntegerField(default=0, verbose_name='Upvotes count'),
        ),
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('report', 'voter')},
            },
        ),
        migrations.AddField(
            model_name='report',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvoted_reports', through='reports.Downvote', through_fields=('report', 'voter'), to=settings.AUTH_USER_MODEL, verbose_name='Downvotes'),
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('report', 'voter')},
            },
        ),
        migrations.AddField(
            model_name='report',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvoted_reports', through='reports.Upvote', through_fields=('report', 'voter'), to=settings.AUTH_USER_MODEL, verbose_name='Upvotes'),
        ),
    ]
