# Generated by Django 5.2.5 on 2025-09-02 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_latitude_remove_report_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='downvotes',
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='report',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='report',
            name='upvotes',
        ),
        migrations.CreateModel(
            name='ReportVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('report', 'voter')},
            },
        ),
        migrations.AddField(
            model_name='report',
            name='votes',
            field=models.ManyToManyField(related_name='upvoted_reports', through='reports.ReportVote', through_fields=('report', 'voter'), to=settings.AUTH_USER_MODEL, verbose_name='Votes'),
        ),
        migrations.DeleteModel(
            name='Downvote',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
