# Generated by Django 5.2.5 on 2025-09-03 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_report_downvotes_alter_upvote_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='votes',
        ),
        migrations.AlterField(
            model_name='reportvote',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reports.report'),
        ),
    ]
