# Generated by Django 5.2.5 on 2025-09-20 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reportvote_updated_at_alter_report_created_at_and_more'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportvote',
            name='voting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='voting.voting'),
        ),
    ]
