# Generated by Django 5.2.5 on 2025-09-21 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_reportvote_voting'),
        ('voting', '0002_voting_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportvote',
            name='voting',
        ),
        migrations.AddField(
            model_name='report',
            name='voting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='voting.voting'),
        ),
    ]
