# Generated by Django 5.2.5 on 2025-09-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_to_be_selected', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Voting',
                'verbose_name_plural': 'Votings',
            },
        ),
    ]
