# Generated by Django 5.2.5 on 2025-09-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
